import type { Video, Channel, Comment } from '@/lib/types';
import { subDays, subHours, subMinutes, subMonths, subWeeks } from 'date-fns';

const now = new Date();

export const channels: Channel[] = [
  {
    id: 'chan-01',
    name: 'CodeWizard',
    avatarUrl: 'https://picsum.photos/seed/avatar01/48/48',
    subscribers: 123000,
    bannerUrl: 'https://picsum.photos/seed/banner01/1280/280',
  },
  {
    id: 'chan-02',
    name: 'FoodieFusion',
    avatarUrl: 'https://picsum.photos/seed/avatar02/48/48',
    subscribers: 45000,
    bannerUrl: 'https://picsum.photos/seed/banner02/1280/280',
  },
  {
    id: 'chan-03',
    name: 'PetPals',
    avatarUrl: 'https://picsum.photos/seed/avatar03/48/48',
    subscribers: 250000,
    bannerUrl: 'https://picsum.photos/seed/banner03/1280/280',
  },
  {
    id: 'chan-04',
    name: 'MusicMinds',
    avatarUrl: 'https://picsum.photos/seed/avatar04/48/48',
    subscribers: 89000,
    bannerUrl: 'https://picsum.photos/seed/banner04/1280/280',
  },
  {
    id: 'chan-05',
    name: 'TravelVibes',
    avatarUrl: 'https://picsum.photos/seed/avatar05/48/48',
    subscribers: 310000,
    bannerUrl: 'https://picsum.photos/seed/banner05/1280/280',
  },
  {
    id: 'chan-06',
    name: 'ArtExplorers',
    avatarUrl: 'https://picsum.photos/seed/avatar06/48/48',
    subscribers: 56000,
    bannerUrl: 'https://picsum.photos/seed/banner06/1280/280',
  },
];

export const videos: Video[] = [
  {
    id: 'vid-01',
    title: 'Building a Next.js App in 10 Minutes',
    description: 'A quick tutorial on how to get started with Next.js and build a simple application from scratch.',
    tags: ['Next.js', 'React', 'JavaScript', 'Web Development'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb01/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-01',
    uploadDate: subDays(now, 2),
    views: 15000,
    likes: 800,
    dislikes: 12,
  },
  {
    id: 'vid-02',
    title: 'The Perfect Pizza Dough Recipe',
    description: 'Learn how to make the perfect pizza dough at home. It\'s easier than you think!',
    tags: ['Cooking', 'Pizza', 'Recipe', 'Food'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb02/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-02',
    uploadDate: subWeeks(now, 1),
    views: 250000,
    likes: 12000,
    dislikes: 150,
  },
  {
    id: 'vid-03',
    title: 'Advanced React Patterns',
    description: 'Dive deep into advanced React patterns like Higher-Order Components, Render Props, and Hooks.',
    tags: ['React', 'JavaScript', 'Programming', 'Advanced'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb03/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-01',
    uploadDate: subMonths(now, 1),
    views: 85000,
    likes: 4200,
    dislikes: 80,
  },
  {
    id: 'vid-04',
    title: 'Funny Dog Moments Compilation',
    description: 'A compilation of the funniest dog moments to brighten your day.',
    tags: ['Dogs', 'Funny', 'Animals', 'Cute'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb04/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-03',
    uploadDate: subDays(now, 5),
    views: 1200000,
    likes: 55000,
    dislikes: 300,
  },
  {
    id: 'vid-05',
    title: 'Acoustic Guitar for Beginners',
    description: 'Learn your first three chords on the acoustic guitar and play thousands of songs.',
    tags: ['Guitar', 'Music', 'Lesson', 'Beginner'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb05/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-04',
    uploadDate: subMonths(now, 3),
    views: 750000,
    likes: 35000,
    dislikes: 450,
  },
  {
    id: 'vid-06',
    title: 'Tokyo at Night: A Cinematic 4K Drone Film',
    description: 'Experience the vibrant nightlife of Tokyo from a unique perspective. Shot on a DJI Mavic 3.',
    tags: ['Travel', 'Japan', 'Tokyo', 'Drone', '4K'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb06/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-05',
    uploadDate: subWeeks(now, 2),
    views: 450000,
    likes: 28000,
    dislikes: 200,
  },
  {
    id: 'vid-07',
    title: 'Watercolor Painting Tutorial: Sunset Landscape',
    description: 'Follow along as I paint a beautiful sunset landscape using watercolors. For all skill levels.',
    tags: ['Art', 'Painting', 'Watercolor', 'Tutorial'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb07/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-06',
    uploadDate: subDays(now, 10),
    views: 45000,
    likes: 2500,
    dislikes: 30,
  },
  {
    id: 'vid-08',
    title: 'Full Body Workout - No Equipment Needed',
    description: 'A 30-minute high-intensity interval training (HIIT) workout you can do at home with no equipment.',
    tags: ['Fitness', 'Workout', 'HIIT', 'Home Workout'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb08/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-05',
    uploadDate: subHours(now, 12),
    views: 9800,
    likes: 750,
    dislikes: 5,
  },
  {
    id: 'vid-09',
    title: 'The Hidden Beaches of the Philippines',
    description: 'Join me as we explore the most beautiful and hidden beaches in the Philippines.',
    tags: ['Travel', 'Philippines', 'Beach', 'Adventure'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb09/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-05',
    uploadDate: subMonths(now, 2),
    views: 980000,
    likes: 45000,
    dislikes: 800,
  },
  {
    id: 'vid-10',
    title: 'Latte Art for Dummies',
    description: 'A step-by-step guide to creating beautiful latte art, even if you\'re a complete beginner.',
    tags: ['Coffee', 'Latte Art', 'Tutorial', 'Barista'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb10/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-02',
    uploadDate: subDays(now, 20),
    views: 120000,
    likes: 6000,
    dislikes: 90,
  },
  {
    id: 'vid-11',
    title: 'How I Read 100 Books a Year',
    description: 'My personal strategies and tips for reading more books and retaining information.',
    tags: ['Reading', 'Books', 'Productivity', 'Self-Help'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb11/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-01',
    uploadDate: subDays(now, 1),
    views: 23000,
    likes: 1500,
    dislikes: 25,
  },
  {
    id: 'vid-12',
    title: 'Why Cats Are Better Than Dogs',
    description: 'A humorous and scientific look at why felines are the superior companion. (Don\'t tell the dogs).',
    tags: ['Cats', 'Funny', 'Animals', 'Debate'],
    thumbnailUrl: 'https://picsum.photos/seed/thumb12/480/270',
    videoUrl: 'placeholder',
    channelId: 'chan-03',
    uploadDate: subHours(now, 6),
    views: 34000,
    likes: 3000,
    dislikes: 500,
  },
];

export const comments: Comment[] = [
    {
      id: 'com-01',
      videoId: 'vid-01',
      channelId: 'chan-02',
      text: 'Great tutorial! Super clear and easy to follow.',
      timestamp: subMinutes(now, 10),
    },
    {
      id: 'com-02',
      videoId: 'vid-01',
      channelId: 'chan-04',
      text: 'Thanks for this! Just what I needed to get started.',
      timestamp: subHours(now, 1),
    },
    {
      id: 'com-03',
      videoId: 'vid-01',
      channelId: 'chan-05',
      text: 'Could you do a video on deploying a Next.js app?',
      timestamp: subDays(now, 1),
    },
    {
      id: 'com-04',
      videoId: 'vid-02',
      channelId: 'chan-01',
      text: 'My pizza has never been better! Thank you!',
      timestamp: subMinutes(now, 30),
    },
    {
        id: 'com-05',
        videoId: 'vid-02',
        channelId: 'chan-03',
        text: 'I burnt it... but I will try again!',
        timestamp: subHours(now, 2),
    },
];

export const watchHistory: string[] = ['vid-01', 'vid-02', 'vid-05', 'vid-09'];
