
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 9002

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".next/functions"
